### ISSUE TITLE
Upnid

### ISSUE THREAD

**Issue by lucasupnid** [woliveiras/nodejs-in-brazil#25]
[Upnid](https://conheca.upnid.com/vaga-para-desenvolvedor-pleno/)

**Comment by thiamsantos** [comment]
Vagas podem de backend podem ser compatilhadas no [backend-br/vagas](https://github.com/backend-br/vagas) e de fron no [frontendbr/vagas](https://github.com/frontendbr/vagas).

**Comment by woliveiras** [comment]
Excelente dica, @thiamsantos 

Pode postar lá, @lucasupnid? 

Valeeus!
